import secrets
import streamlit as st

# Configuration
BITS_PER_WORD = 11
TARGET_WORDS = 12
EXACT_WORDLIST_SIZE = 1 << BITS_PER_WORD  # Exactly 2048 words
ENTROPY_BYTES = 17  # 136 bits -> slice first 132 bits (12 * 11)

st.set_page_config(
    page_title="128-Bit CSPRNG Generator",
    page_icon="🔐",
    layout="centered",
)

# ------------------------------------------------------------------------------
# State Initialization (History Stack)
# ------------------------------------------------------------------------------
if "history" not in st.session_state:
    st.session_state.history = []
if "current_output" not in st.session_state:
    st.session_state.current_output = None

# ------------------------------------------------------------------------------
# UI Layout
# ------------------------------------------------------------------------------
st.title("🔐 Zero-Bias 128-Bit Generator")

st.warning(
    "⚠️ **Run this locally / offline only.** This tool generates secret key material. "
    "Do not use a phrase generated by a networked instance for real funds."
)

raw_text = st.text_area(
    f"Word List (Requires EXACTLY {EXACT_WORDLIST_SIZE} unique words for zero bias):",
    height=150,
    placeholder="Enter your 2,048 words here...",
)

# Parse raw words preserving exact input order
parsed_words = [
    w.strip().lower()
    for w in raw_text.replace(",", " ").split()
    if w.strip()
]

total_parsed = len(parsed_words)
unique_words = set(parsed_words)
has_duplicates = len(parsed_words) != len(unique_words)

# Status & Bias Checks
is_valid_pool = False

if total_parsed > 0:
    if has_duplicates:
        st.error(
            f"❌ **Duplicate Words Detected:** Input contains {total_parsed} words, "
            f"but only {len(unique_words)} are unique. Remove duplicates to avoid order skew."
        )
    elif total_parsed != EXACT_WORDLIST_SIZE:
        st.warning(
            f"⚠️ **Word Count Mismatch:** Provided **{total_parsed}** words. "
            f"You need **exactly {EXACT_WORDLIST_SIZE} unique words** to guarantee zero selection/truncation bias."
        )
    else:
        is_valid_pool = True
        st.success(
            f"✅ **Zero-Bias Pool Verified:** Exactly **{EXACT_WORDLIST_SIZE}** unique words loaded. "
            f"1:1 uniform mapping active."
        )

# Action Buttons Area
col_gen, col_h1, col_h2 = st.columns([2, 1, 1])

with col_gen:
    generate_btn = st.button(
        "🎲 Generate New 12 Words", 
        type="primary", 
        use_container_width=True,
        disabled=not is_valid_pool
    )

with col_h1:
    has_prev1 = len(st.session_state.history) >= 1
    if st.button("⬅️ Past Gen 1", disabled=not has_prev1, use_container_width=True):
        st.session_state.current_output = st.session_state.history[-1]

with col_h2:
    has_prev2 = len(st.session_state.history) >= 2
    if st.button("⏪ Past Gen 2", disabled=not has_prev2, use_container_width=True):
        st.session_state.current_output = st.session_state.history[-2]

# ------------------------------------------------------------------------------
# Generation Logic
# ------------------------------------------------------------------------------
if generate_btn and is_valid_pool:
    # 1. Cryptographically secure entropy stream
    raw_bytes = secrets.token_bytes(ENTROPY_BYTES)
    bit_string = bin(int.from_bytes(raw_bytes, "big"))[2:].zfill(ENTROPY_BYTES * 8)

    # 2. Slice exact 11-bit chunks -> 0 to 2047 index range
    selected_words = []
    for i in range(TARGET_WORDS):
        chunk = bit_string[i * BITS_PER_WORD : (i + 1) * BITS_PER_WORD]
        idx = int(chunk, 2)  # Strict range 0..2047, perfectly uniform
        selected_words.append(parsed_words[idx])

    new_phrase = " ".join(selected_words)

    # Keep last 10 generations
    st.session_state.history.append(new_phrase)
    if len(st.session_state.history) > 10:
        st.session_state.history.pop(0)

    st.session_state.current_output = new_phrase

# ------------------------------------------------------------------------------
# Results & History Inspection
# ------------------------------------------------------------------------------
if st.session_state.current_output:
    st.subheader("Selected 12-Word Sequence:")
    st.code(st.session_state.current_output, language=None)
    st.caption("Tip: Click the copy icon in the top right of the box above.")
    st.info(
        "🔒 **Zero-Bias Mathematical Guarantee:** OS CSPRNG (`secrets.token_bytes`) -> "
        "11-bit chunks map 1:1 onto 2,048 indices ($P(x) = \\frac{1}{2048}$). No modulo, no truncation."
    )

# Sidebar History Log
with st.sidebar:
    st.header("📜 Generation History")
    if not st.session_state.history:
        st.write("No history generated yet.")
    else:
        for idx, item in enumerate(reversed(st.session_state.history)):
            gen_num = len(st.session_state.history) - idx
            st.text(f"Gen #{gen_num}:")
            st.code(item, language=None)
