import secrets
import streamlit as st

# --- Constants ---
# 17 bytes = 136 bits from CSPRNG.
# We consume exactly 12 × 11 = 132 bits and discard the remaining 4 bits.
ENTROPY_BYTES = 17
BITS_PER_WORD = 11          # 2¹¹ = 2048
WORDS_NEEDED = 12
MIN_WORDLIST_SIZE = 1 << BITS_PER_WORD   # 2048

st.set_page_config(page_title="Mnemonic Generator", page_icon="🔐")
st.title("🔐 12-Word CSPRNG Mnemonic Generator")

st.warning(
    "⚠️ **Run this locally / offline only.** This tool generates secret key "
    "material. If deployed as a hosted web app, the phrase can be exposed via "
    "network transit, server logs, reverse proxies, or browser caches/extensions. "
    "Do not use a phrase generated by a networked instance for real funds."
)

st.caption(
    f"Draws {ENTROPY_BYTES * 8} bits from the OS CSPRNG (`secrets.token_bytes`) "
    f"and uses the first {WORDS_NEEDED * BITS_PER_WORD} bits "
    f"({WORDS_NEEDED} × {BITS_PER_WORD}-bit indices). "
    "This is **not** BIP-39: there is no checksum word and the word list is user-supplied. "
    "It is incompatible with standard hardware/software wallets."
)

raw_text = st.text_area(
    f"Word List (must contain at least {MIN_WORDLIST_SIZE} unique words):",
    height=200,
    placeholder="Paste or type words separated by spaces, commas, or newlines…"
)

# Normalize: lower-case, strip, drop empties, preserve first-seen order, remove duplicates
words = list(dict.fromkeys(
    w.strip().lower()
    for w in raw_text.replace(",", " ").replace("\n", " ").split()
    if w.strip()
))

if len(words) < MIN_WORDLIST_SIZE:
    st.error(
        f"Current pool: **{len(words)}** unique words. "
        f"You need at least **{MIN_WORDLIST_SIZE}** so every {BITS_PER_WORD}-bit "
        "index (0–2047) maps to a distinct word with zero modulo bias."
    )
else:
    st.success(f"Pool size verified: **{len(words)}** unique words (≥ {MIN_WORDLIST_SIZE}).")

if st.button("Generate Secure 12 Words", type="primary"):
    if len(words) < MIN_WORDLIST_SIZE:
        st.error("Cannot generate: word list does not meet the security threshold.")
    else:
        # Cryptographically secure random bytes
        raw = secrets.token_bytes(ENTROPY_BYTES)
        entropy_int = int.from_bytes(raw, byteorder="big")

        selected = []
        for i in range(WORDS_NEEDED):
            # Extract the next 11 bits (most-significant first)
            shift = (ENTROPY_BYTES * 8) - (i + 1) * BITS_PER_WORD
            index = (entropy_int >> shift) & ((1 << BITS_PER_WORD) - 1)  # 0 … 2047
            selected.append(words[index])

        st.code(" ".join(selected), language=None)

        st.info(
            "Entropy source: OS CSPRNG via `secrets.token_bytes`. "
            f"Exactly {WORDS_NEEDED * BITS_PER_WORD} bits used. "
            "Because the word pool contains ≥ 2048 entries, each 11-bit index "
            "maps 1:1 onto a word — no modulo reduction, no bias."
        )
