import secrets
import streamlit as st

# Configuration
ENTROPY_BYTES = 17          # 136 bits → take first 132 bits (12 × 11)
BITS_PER_WORD = 11
TARGET_WORDS = 12
MIN_WORDLIST_SIZE = 1 << BITS_PER_WORD  # 2048

st.set_page_config(
    page_title="128-Bit CSPRNG Generator",
    page_icon="🔐",
    layout="centered",
)

# ------------------------------------------------------------------------------
# State Initialization (History Stack)
# ------------------------------------------------------------------------------
if "history" not in st.session_state:
    st.session_state.history = []
if "current_output" not in st.session_state:
    st.session_state.current_output = None

# ------------------------------------------------------------------------------
# UI Layout
# ------------------------------------------------------------------------------
st.title("🔐 128-Bit Generator with History")

st.warning(
    "⚠️ **Run this locally / offline only.** This tool generates secret key material. "
    "Do not use a phrase generated by a networked instance for real funds."
)

raw_text = st.text_area(
    f"Word List (Requires {MIN_WORDLIST_SIZE} unique words for full 128-bit security):",
    height=150,
    placeholder="Enter your words here...",
)

words = list(
    dict.fromkeys(
        w.strip().lower()
        for w in raw_text.replace(",", " ").split()
        if w.strip()
    )
)
word_count = len(words)

# Status Checks
if word_count > 0:
    if word_count < MIN_WORDLIST_SIZE:
        st.warning(
            f"Current pool: **{word_count}** words. "
            f"You need **{MIN_WORDLIST_SIZE} unique words** for true 128-bit security "
            f"(no modulo bias)."
        )
    else:
        st.success(
            f"Pool size verified: **{word_count}** words "
            f"(≥ {BITS_PER_WORD} bits/word, zero bias)."
        )

# Action Buttons Area
col_gen, col_h1, col_h2 = st.columns([2, 1, 1])

with col_gen:
    generate_btn = st.button(
        "🎲 Generate New 12 Words", type="primary", use_container_width=True
    )

with col_h1:
    has_prev1 = len(st.session_state.history) >= 1
    if st.button("⬅️ Past Gen 1", disabled=not has_prev1, use_container_width=True):
        st.session_state.current_output = st.session_state.history[-1]

with col_h2:
    has_prev2 = len(st.session_state.history) >= 2
    if st.button("⏪ Past Gen 2", disabled=not has_prev2, use_container_width=True):
        st.session_state.current_output = st.session_state.history[-2]

# ------------------------------------------------------------------------------
# Generation Logic
# ------------------------------------------------------------------------------
if generate_btn:
    if word_count < MIN_WORDLIST_SIZE:
        st.error(
            f"Cannot generate securely: need at least {MIN_WORDLIST_SIZE} unique words. "
            "Using fewer words (or applying modulo) introduces bias and reduces entropy."
        )
    else:
        # Cryptographically secure entropy
        raw_bytes = secrets.token_bytes(ENTROPY_BYTES)
        bit_string = bin(int.from_bytes(raw_bytes, "big"))[2:].zfill(ENTROPY_BYTES * 8)

        selected_words = []
        for i in range(TARGET_WORDS):
            chunk = bit_string[i * BITS_PER_WORD : (i + 1) * BITS_PER_WORD]
            idx = int(chunk, 2)               # 0–2047, direct mapping, no modulo
            selected_words.append(words[idx])

        new_phrase = " ".join(selected_words)

        # Keep last 10 generations
        st.session_state.history.append(new_phrase)
        if len(st.session_state.history) > 10:
            st.session_state.history.pop(0)

        st.session_state.current_output = new_phrase

# ------------------------------------------------------------------------------
# Results & History Inspection
# ------------------------------------------------------------------------------
if st.session_state.current_output:
    st.subheader("Selected 12-Word Sequence:")
    st.code(st.session_state.current_output, language=None)
    st.caption("Tip: Click the copy icon in the top right of the box above.")
    st.info(
        "Entropy source: OS CSPRNG (`secrets.token_bytes`). "
        "Each 11-bit index maps 1:1 onto a word — no modulo reduction, no bias."
    )

# Sidebar History Log
with st.sidebar:
    st.header("📜 Generation History")
    if not st.session_state.history:
        st.write("No history generated yet.")
    else:
        for idx, item in enumerate(reversed(st.session_state.history)):
            gen_num = len(st.session_state.history) - idx
            st.text(f"Gen #{gen_num}:")
            st.code(item, language=None)
